- hosts: all

  become: true
  become_user: root

  # Ansible tasks starts here..
  tasks:

      - name: Insert fastcgi caching config in /etc/nginx/sites-available/default
        blockinfile:
          path: /etc/nginx/sites-available/default
          # state: absent
          marker: "### {mark} - Part 1 - Insert fastcgi module config - ANSIBLE MANAGED BLOCK ###"
          insertbefore: '^server {'
          block: |
            fastcgi_cache_path /etc/nginx/cache levels=1:2 keys_zone=MY_CACHE:100m inactive=60m;
            fastcgi_cache_key "$scheme$request_method$host$request_uri";


      - name: Part 2 Insert fastcgi caching config in /etc/nginx/sites-available/default
        blockinfile:
            path: /etc/nginx/sites-available/default
            # state: absent
            marker: "               ### {mark} - Part2 - Insert fastcgi module config - ANSIBLE MANAGED BLOCK ###"
            insertafter: "fastcgi_pass unix:/run/php/php7.4-fpm.sock;"
            block: |
                             include fastcgi_params;
                             fastcgi_cache MY_CACHE;
                             fastcgi_cache_valid 200 60m;
                             add_header jmc-lxd-X-Cache $upstream_cache_status;

      - name: Test and reload nginx
        shell: 'nginx -t; systemctl reload nginx'
