- hosts: all
  vars:
    ansible_host_key_checking: false

    # Workaround if LXC target host does not have python 3 (not by default)
    ansible_python_interpreter: "/usr/bin/python3"

    #  vars_files:
    # - vars.yml

  become: true
  become_user: root

  # Ansible tasks stars here..
  tasks:


    # -- START Install Required repo and updates.
    # Required for PHP FPM
    - name: Getting the php version
      shell: "ps -aux | grep /etc/php/ | grep -v grep | awk '{print $14}' | awk -F'/' '{print $4}'"
      register: phpversion

    - name: Updating php.ini memory_limi
      ini_file:
          path: /etc/php/{{ phpversion.stdout }}/fpm/php.ini
          section: PHP
          option: memory_limit
          value: 512M

    - name: Restart PHP
      shell: "systemctl restart php{{ phpversion.stdout }}-fpm"
